import {Word} from '../entity/Word';

export const mockWords: Word[] = [
    {en:"abbreviation",zh: " n．缩短，缩写", wrongTime: 0},
    {en:"abide ",zh: " v．容忍，忍受", wrongTime: 0},
    {en:"abolish",zh: "  vt．废止", wrongTime: 0},
    {en:"absent",zh: "  a．不在场的；缺乏的", wrongTime: 0},
    {en:"absorption",zh: " n．吸收；专注", wrongTime: 0},
    {en:"abstract",zh: "  vt．摘要", wrongTime: 0},
    {en:"absurd",zh: " adj．荒谬的，可笑的", wrongTime: 0},
    {en:"abundance",zh: " n．充裕，多量", wrongTime: 0},
    {en:"accessory",zh: " adj．附属的", wrongTime: 0},
    {en:"accord ",zh: " v．同意，给予", wrongTime: 0},
    {en:"acknowledge",zh: "  vt．承认", wrongTime: 0},
    {en:"acquaint",zh: "  vt．使认识，使了解", wrongTime: 0},
    {en:"action",zh: " n．行动；作用；功能", wrongTime: 0},
    {en:"adhere ",zh: " v．粘着", wrongTime: 0},
    {en:"adjacent",zh: " adj．毗连的，接近的", wrongTime: 0},
    {en:"adjoin ",zh: " v．邻接", wrongTime: 0},
    {en:"adjustable",zh: "  a．可调整的，可校准的", wrongTime: 0},
    {en:"administration",zh: " n．管理；管理部门", wrongTime: 0},
    {en:"admiration",zh: " n．钦佩；赞美，羡慕", wrongTime: 0},
    {en:"adoption",zh: " n．收养；采纳，采取", wrongTime: 0},
    {en:"adore",zh: "  vt．崇拜", wrongTime: 0},
    {en:"advantageous",zh: "  a．有利的，有助的", wrongTime: 0},
    {en:"advertise",zh: "  vt．做广告", wrongTime: 0},
    {en:"advocate",zh: "  vt．主张", wrongTime: 0},
    {en:"aerial",zh: " adj．空中的", wrongTime: 0},
    {en:"aerospace",zh: " n．航空和宇宙航行空间", wrongTime: 0},
    {en:"affirm",zh: "  vt．断言，批准；证实", wrongTime: 0},
    {en:"agitation",zh: " n．鼓动，焦虑", wrongTime: 0},
    {en:"agreeable",zh: "  a．惬意的；同意的", wrongTime: 0},
    {en:"album",zh: " n．粘贴簿；相册；文选", wrongTime: 0},
    {en:"alert",zh: "  a．警惕的；活跃的", wrongTime: 0},
    {en:"algebra",zh: " n．代数学", wrongTime: 0},
    {en:"alien",zh: "  a．外国的 n.外国人", wrongTime: 0},
    {en:"alignment",zh: " n．队列；结盟，联合", wrongTime: 0},
    {en:"allied",zh: "  a．联合的；联姻的", wrongTime: 0},
    {en:"allowance",zh: " n．津贴", wrongTime: 0},
    {en:"ally",zh: " n．盟国，支持者", wrongTime: 0},
    {en:"alteration",zh: " n．改变，变更", wrongTime: 0},
    {en:"alternate",zh: "  vt．使交替 a.交替的", wrongTime: 0},
    {en:"amateur",zh: "  a．业余的n.业余爱好者", wrongTime: 0},
    {en:"ambassador",zh: " n．大使，使节", wrongTime: 0},
    {en:"ambient",zh: "  a．周围的，包围着的", wrongTime: 0},
    {en:"ambiguous",zh: " adj．含糊的，不明确的", wrongTime: 0},
    {en:"ambitious",zh: "  a．有雄心的；热望的", wrongTime: 0},
    {en:"ample",zh: " adj．富足的，充足的", wrongTime: 0},
    {en:"amplitude",zh: " n．广大；充足；振幅", wrongTime: 0},
    {en:"amusement",zh: " n．娱乐，消遣，乐趣", wrongTime: 0},
    {en:"analogue",zh: " n．类似物；同源语", wrongTime: 0},
    {en:"analogy",zh: " n．类似，相似，类比，类推", wrongTime: 0},
    {en:"analytic(al)",zh: "  a．分析的；分解的", wrongTime: 0},
    {en:"anniversary",zh: " n．周年纪念日", wrongTime: 0},
    {en:"announce",zh: "  vt．宣布，宣告，发表", wrongTime: 0},
    {en:"anode",zh: " n．(电)阳极，正极", wrongTime: 0},
    {en:"answer",zh: "  vt．回答；响应；适应 vi.符合，适合", wrongTime: 0},
    {en:"Antarctic",zh: "  a．南极的 n.南极区", wrongTime: 0},
    {en:"antenna",zh: " n．触角，无线", wrongTime: 0},
    {en:"antique",zh: " n．古物", wrongTime: 0},
    {en:"apparent",zh: "  a．明显的", wrongTime: 0},
    {en:"appendix",zh: " n．附录，附属物；阑尾", wrongTime: 0},
    {en:"applaud",zh: "  vt．喝彩；欢呼vi.欢呼", wrongTime: 0},
    {en:"applause",zh: " n．鼓掌", wrongTime: 0},
    {en:"appreciable",zh: " adj．可感知的", wrongTime: 0},
    {en:"appreciation",zh: " n．欣赏；鉴别；感激", wrongTime: 0},
    {en:"apt",zh: " adj．易于...", wrongTime: 0},
]
